use_frameworks!

target 'TDDBServiceKeychainSwift_Example' do
  pod 'TDDBServiceKeychainSwift', :path => '../'

  target 'TDDBServiceKeychainSwift_Tests' do
    inherit! :search_paths

    
  end
end
